services:
  postgresql:
    container_name: bdd_oltp
    image: postgres:17
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${PostgreSql_User}
      POSTGRES_PASSWORD: ${PostgreSql_Password}
      POSTGRES_DB: ${PostgreSql_Database}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - reaseau_projet

  clickhouse:
    container_name: bdd_olap
    image: clickhouse/clickhouse-server:23.8
    env_file:
      - .env
    environment: 
      CLICKHOUSE_USER: ${ClickHouse_User} 
      CLICKHOUSE_PASSWORD: ${ClickHouse_Password}  
      CLICKHOUSE_DB: ${ClickHouse_Database}
      CLICKHOUSE_DEFAULT_DB: ${ClickHouse_Database}
    restart: unless-stopped
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - clickhouse_data:/var/lib/clickhouse
    networks:
      - reaseau_projet

  api_gateway:
    container_name: api_gateway
    build:
      context: ../backend/apiGateway
    env_file:
      - ../backend/apiGateway/environnements/.env
    volumes:
      - ../backend/apiGateway:/usr/src/app
    ports:
      - 3001:3001
    networks:
      - reaseau_projet
    command: [ "sh", "./install.sh" ] 

  api_oltp:
    container_name: api_oltp
    build:
      context: ../backend/apiPostgreSql
    env_file:
      - ../backend/apiPostgreSql/environnements/.env
    volumes:
      - ../backend/apiPostgreSql:/usr/src/app
    ports:
      - 3002:3002
    depends_on:
      - postgresql
    networks:
      - reaseau_projet
    command: [ "sh", "./install.sh", "bdd_oltp" ]

  api_olap:
    container_name: api_olap
    build:
      context: ../backend/apiClickHouse
    env_file:
      - ../backend/apiClickHouse/environnements/.env
    volumes:
      - ../backend/apiClickHouse:/usr/src/app
    ports:
      - 3003:3003
    depends_on:
      - clickhouse
    networks:
      - reaseau_projet
    command: [ "sh", "./install.sh", "bdd_olap" ]

  # Pour créer un network : docker network create "nom_du_reseau"
networks:
  reaseau_projet:
    driver: bridge
    external: true

volumes:
  postgres_data:
  clickhouse_data:
